/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CreateRouteImport } from './routes/create'
import { Route as LeadersRouteImport } from './routes/leaders'
import { Route as MeRouteImport } from './routes/me'
import { Route as PetitionsRouteImport } from './routes/petitions'
import { Route as ApiAuthRouteImport } from './routes/api/auth'
import { Route as ApiClaimLeaderRouteImport } from './routes/api/claim-leader'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiPetitionsRouteImport } from './routes/api/petitions'
import { Route as ApiProfileRouteImport } from './routes/api/profile'
import { Route as ApiResponsesRouteImport } from './routes/api/responses'
import { Route as ApiSignaturesRouteImport } from './routes/api/signatures'
import { Route as ApiStateRouteImport } from './routes/api/state'
import { Route as PSlugRouteImport } from './routes/p.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadersRoute = LeadersRouteImport.update({
  id: '/leaders',
  path: '/leaders',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const PetitionsRoute = PetitionsRouteImport.update({
  id: '/petitions',
  path: '/petitions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClaimLeaderRoute = ApiClaimLeaderRouteImport.update({
  id: '/api/claim-leader',
  path: '/api/claim-leader',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPetitionsRoute = ApiPetitionsRouteImport.update({
  id: '/api/petitions',
  path: '/api/petitions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResponsesRoute = ApiResponsesRouteImport.update({
  id: '/api/responses',
  path: '/api/responses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSignaturesRoute = ApiSignaturesRouteImport.update({
  id: '/api/signatures',
  path: '/api/signatures',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStateRoute = ApiStateRouteImport.update({
  id: '/api/state',
  path: '/api/state',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/create': typeof CreateRoute
  '/leaders': typeof LeadersRoute
  '/me': typeof MeRoute
  '/petitions': typeof PetitionsRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/claim-leader': typeof ApiClaimLeaderRoute
  '/api/health': typeof ApiHealthRoute
  '/api/petitions': typeof ApiPetitionsRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/responses': typeof ApiResponsesRoute
  '/api/signatures': typeof ApiSignaturesRoute
  '/api/state': typeof ApiStateRoute
  '/p/$slug': typeof PSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/create': typeof CreateRoute
  '/leaders': typeof LeadersRoute
  '/me': typeof MeRoute
  '/petitions': typeof PetitionsRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/claim-leader': typeof ApiClaimLeaderRoute
  '/api/health': typeof ApiHealthRoute
  '/api/petitions': typeof ApiPetitionsRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/responses': typeof ApiResponsesRoute
  '/api/signatures': typeof ApiSignaturesRoute
  '/api/state': typeof ApiStateRoute
  '/p/$slug': typeof PSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/create': typeof CreateRoute
  '/leaders': typeof LeadersRoute
  '/me': typeof MeRoute
  '/petitions': typeof PetitionsRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/claim-leader': typeof ApiClaimLeaderRoute
  '/api/health': typeof ApiHealthRoute
  '/api/petitions': typeof ApiPetitionsRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/responses': typeof ApiResponsesRoute
  '/api/signatures': typeof ApiSignaturesRoute
  '/api/state': typeof ApiStateRoute
  '/p/$slug': typeof PSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/create'
    | '/leaders'
    | '/me'
    | '/petitions'
    | '/api/auth'
    | '/api/claim-leader'
    | '/api/health'
    | '/api/petitions'
    | '/api/profile'
    | '/api/responses'
    | '/api/signatures'
    | '/api/state'
    | '/p/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/create'
    | '/leaders'
    | '/me'
    | '/petitions'
    | '/api/auth'
    | '/api/claim-leader'
    | '/api/health'
    | '/api/petitions'
    | '/api/profile'
    | '/api/responses'
    | '/api/signatures'
    | '/api/state'
    | '/p/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/create'
    | '/leaders'
    | '/me'
    | '/petitions'
    | '/api/auth'
    | '/api/claim-leader'
    | '/api/health'
    | '/api/petitions'
    | '/api/profile'
    | '/api/responses'
    | '/api/signatures'
    | '/api/state'
    | '/p/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  CreateRoute: typeof CreateRoute
  LeadersRoute: typeof LeadersRoute
  MeRoute: typeof MeRoute
  PetitionsRoute: typeof PetitionsRoute
  ApiAuthRoute: typeof ApiAuthRoute
  ApiClaimLeaderRoute: typeof ApiClaimLeaderRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiPetitionsRoute: typeof ApiPetitionsRoute
  ApiProfileRoute: typeof ApiProfileRoute
  ApiResponsesRoute: typeof ApiResponsesRoute
  ApiSignaturesRoute: typeof ApiSignaturesRoute
  ApiStateRoute: typeof ApiStateRoute
  PSlugRoute: typeof PSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaders': {
      id: '/leaders'
      path: '/leaders'
      fullPath: '/leaders'
      preLoaderRoute: typeof LeadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/petitions': {
      id: '/petitions'
      path: '/petitions'
      fullPath: '/petitions'
      preLoaderRoute: typeof PetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/claim-leader': {
      id: '/api/claim-leader'
      path: '/api/claim-leader'
      fullPath: '/api/claim-leader'
      preLoaderRoute: typeof ApiClaimLeaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/petitions': {
      id: '/api/petitions'
      path: '/api/petitions'
      fullPath: '/api/petitions'
      preLoaderRoute: typeof ApiPetitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/responses': {
      id: '/api/responses'
      path: '/api/responses'
      fullPath: '/api/responses'
      preLoaderRoute: typeof ApiResponsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/signatures': {
      id: '/api/signatures'
      path: '/api/signatures'
      fullPath: '/api/signatures'
      preLoaderRoute: typeof ApiSignaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/state': {
      id: '/api/state'
      path: '/api/state'
      fullPath: '/api/state'
      preLoaderRoute: typeof ApiStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  CreateRoute: CreateRoute,
  LeadersRoute: LeadersRoute,
  MeRoute: MeRoute,
  PetitionsRoute: PetitionsRoute,
  ApiAuthRoute: ApiAuthRoute,
  ApiClaimLeaderRoute: ApiClaimLeaderRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiPetitionsRoute: ApiPetitionsRoute,
  ApiProfileRoute: ApiProfileRoute,
  ApiResponsesRoute: ApiResponsesRoute,
  ApiSignaturesRoute: ApiSignaturesRoute,
  ApiStateRoute: ApiStateRoute,
  PSlugRoute: PSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
